# This is a basic workflow to help you get started with Actions

name: slack

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # 只要 push 就 trigger flow，不論是哪一個分支
  push:

  # Allows you to run this workflow manually from the Actions tab
  # 可以手動 trigger workflow
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # job 的代號
  slackNotification:
    # job 的名字
    name: Slack Notification

    # job 在甚麼作業系統上面執行
    runs-on: ubuntu-latest

    # job 裡面要做哪些步驟 (steps)
    steps:
      # 步驟1 的名字
    - name: checkout

      # 把 $GITHUB_WORKSPACE 裡面的 repository，check-out 出來，給 job 使用
      uses: actions/checkout@v2

    # 步驟2 的名字
    - name: Slack Notification

      # 呼叫 rtCamp/action-slack-notify@v2 這個功能
      uses: rtCamp/action-slack-notify@v2

      # 設定環境變數
      env:
        # secrets 是一個加密金鑰，存在其他地方，不會存在 GitHub 上面
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#3278BD'
        SLACK_CHANNEL: random
        SLACK_USERNAME: GITHUB_BOT
